### ISSUE TITLE
Rubygems release?

### ISSUE THREAD

**Issue by eimermusic** [johanhalse/bankid#6]
I was just wondering why the latest revisions (2.x) are not on Rubygems?
Oversight or some issue or?

**Comment by johanhalse** [comment]
No, it's because I'm still sort of considering the API. If I'm doing a major version bump I might as well give it a little more thought! The general idea going forward is to lose the multiple fields and instead rely on a `state` so you don't have to check for both errors and completeness etc. The last abstraction was probably a little too close to the API implementation for my taste.

The reason it's happening is that I'm implementing BankID in a second app now and I was sort of annoyed. I'll probably cut a new release Soon™ and hopefully it'll be a little easier to work with.

**Comment by eimermusic** [comment]
Ok. No problem.
